/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

import type { HyperframesSettings } from "./types";

export const DEFAULT_HYPERFRAMES_SETTINGS: HyperframesSettings = {
  template: "title", title: "A clear title", subtitle: "A concise supporting line", accent: "#7c3aed", background: "#09090b", duration: 5, width: 1920, height: 1080, fps: 30, transparent: false,
};

function html(value: string): string { return value.replace(/[&<>\"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[character]!); }
function color(value: string, fallback: string): string { return /^#[0-9a-f]{3,8}$/i.test(value) ? value : fallback; }
function number(value: number, fallback: number, minimum: number): number { return Number.isFinite(value) && value >= minimum ? value : fallback; }
function values(settings: HyperframesSettings) {
  return { title: html(settings.title), subtitle: html(settings.subtitle), accent: color(settings.accent, DEFAULT_HYPERFRAMES_SETTINGS.accent), background: settings.transparent ? "transparent" : color(settings.background, DEFAULT_HYPERFRAMES_SETTINGS.background), duration: number(settings.duration, 5, .1), width: number(settings.width, 1920, 16), height: number(settings.height, 1080, 16), fps: number(settings.fps, 30, 1) };
}
function page(title: string, body: string, style: string, animation: string): string {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title><style>${style}</style></head><body>${body}<script>const motion=(selector,keyframes,timing)=>{const animation=document.querySelector(selector).animate(keyframes,{fill:"both",iterations:1,...timing});animation.pause();};${animation}</script></body></html>`;
}

/** Generates one compact, local, seek-safe editable composition. */
export function generateTemplate(settings: HyperframesSettings): string {
  const s = values(settings);
  const root = `id="root" data-composition-id="main" data-start="0" data-width="${s.width}" data-height="${s.height}" data-duration="${s.duration}" data-fps="${s.fps}"`;
  const base = `*{box-sizing:border-box}html,body{margin:0;width:100%;height:100%;overflow:hidden;background:transparent;font-family:Inter,Arial,sans-serif}#root{position:relative;width:${s.width}px;height:${s.height}px;overflow:hidden;container-type:size}.clip,.backdrop{position:absolute;inset:0}.backdrop{background:${s.background}}.copy{position:absolute;color:#fff;min-width:0;overflow-wrap:anywhere}.clip{overflow:hidden}`;
  if (settings.template === "lower-third") {
    return page("Lower third", `<div ${root}><div class="backdrop"></div><section class="clip" data-start="0" data-duration="${s.duration}" data-track-index="1"><div class="bar"></div><div class="copy"><p id="title">${s.title}</p><p id="subtitle">${s.subtitle}</p></div></section></div>`, `${base}.backdrop{opacity:${settings.transparent ? 0 : 1}}.bar{position:absolute;left:0;bottom:10.9cqh;width:min(76cqw,100%);height:15.9cqh;background:${s.accent};transform-origin:left center}.copy{left:4.5cqw;bottom:13.4cqh;max-width:66cqw}.copy p{margin:0}.copy #title{font-size:min(3.25cqw,6.5cqh);font-weight:750;line-height:1.02;letter-spacing:-.04em}.copy #subtitle{margin-top:min(1cqw,2cqh);font-size:min(1.46cqw,2.9cqh);line-height:1.15;opacity:.84}`, `motion(".bar",[{transform:"scaleX(0)"},{transform:"scaleX(1)"}],{duration:500,delay:150,easing:"cubic-bezier(.2,0,0,1)"});motion(".copy",[{transform:"translateX(-34px)",opacity:0},{transform:"translateX(0)",opacity:1}],{duration:500,delay:350,easing:"cubic-bezier(.2,0,0,1)"});motion(".copy",[{transform:"translateX(0)",opacity:1},{transform:"translateX(-34px)",opacity:0}],{duration:350,delay:${Math.round(Math.max(.8,s.duration-.55)*1000)},easing:"cubic-bezier(.4,0,1,1)"});`);
  }
  if (settings.template === "stat") {
    return page("Stat card", `<div ${root}><div class="backdrop"></div><section class="clip" data-start="0" data-duration="${s.duration}" data-track-index="1"><div class="halo"></div><article class="card"><p id="title">${s.title}</p><strong id="stat">${s.subtitle}</strong><span></span></article></section></div>`, `${base}.halo{position:absolute;width:43cqw;height:76cqh;right:-7cqw;top:-21cqh;border-radius:50%;background:${s.accent};opacity:.22}.card{position:absolute;left:7.3cqw;right:15cqw;top:15.7cqh;min-height:55cqh;padding:clamp(18px,4.8cqw,92px);background:#fff;color:#111827;border-radius:min(2.2cqw,4.4cqh);box-shadow:0 min(1.9cqw,3.7cqh) min(5.2cqw,10.2cqh) #0005}.card p{margin:0;color:#52525b;font-size:min(1.88cqw,3.75cqh);font-weight:700;line-height:1.12}.card strong{display:block;margin-top:min(1.4cqw,2.8cqh);font-size:min(10.5cqw,18cqh);line-height:.92;letter-spacing:-.07em;overflow-wrap:anywhere}.card span{display:block;margin-top:min(2.4cqw,4.7cqh);width:min(6.7cqw,13.3cqh);height:min(.75cqw,1.5cqh);border-radius:99px;background:${s.accent}}`, `motion(".card",[{transform:"translateY(70px) scale(.94)",opacity:0},{transform:"translateY(0) scale(1)",opacity:1}],{duration:700,delay:100,easing:"cubic-bezier(.2,0,0,1)"});motion("#stat",[{transform:"translateY(28px)",opacity:0},{transform:"translateY(0)",opacity:1}],{duration:450,delay:400,easing:"cubic-bezier(.2,0,0,1)"});motion(".card span",[{transform:"scaleX(0)"},{transform:"scaleX(1)"}],{duration:400,delay:550,easing:"cubic-bezier(.2,0,0,1)"});`);
  }
  if (settings.template === "custom") return "";
  return page("Title card", `<div ${root}><section class="clip" data-start="0" data-duration="${s.duration}" data-track-index="1"><div class="backdrop wash"></div><div class="copy"><p id="eyebrow">${s.subtitle}</p><h1 id="title">${s.title}</h1><i></i></div></section></div>`, `${base}.wash{background:${s.background};background-image:radial-gradient(circle at 78% 22%,${s.accent},transparent 42%)}.copy{left:7.8cqw;right:7.8cqw;top:50%;transform:translateY(-50%)}.copy p{margin:0 0 min(1.5cqw,3cqh);font-size:min(1.56cqw,3.1cqh);line-height:1.14;font-weight:700;letter-spacing:.14em;text-transform:uppercase;opacity:.78}.copy h1{margin:0;max-width:78cqw;font-size:min(7.1cqw,14cqh);line-height:.94;letter-spacing:-.065em;overflow-wrap:anywhere}.copy i{display:block;margin-top:min(2.8cqw,5.5cqh);width:min(8.9cqw,17.8cqh);height:min(.73cqw,1.45cqh);border-radius:99px;background:${s.accent}}`, `motion("#eyebrow",[{transform:"translateY(24px)",opacity:0},{transform:"translateY(0)",opacity:1}],{duration:450,delay:200,easing:"cubic-bezier(.2,0,0,1)"});motion("#title",[{transform:"translateY(70px)",opacity:0},{transform:"translateY(0)",opacity:1}],{duration:700,delay:320,easing:"cubic-bezier(.2,0,0,1)"});motion(".copy i",[{transform:"scaleX(0)"},{transform:"scaleX(1)"}],{duration:450,delay:700,easing:"cubic-bezier(.2,0,0,1)"});`);
}
